### ISSUE TITLE
does nor work for me

### ISSUE THREAD

**Issue by ghost** [Thysbelon/gbaconv-web#13]
home/web_user/savedata.srm
255
255
255
255
255
255
255
255
255
255

**Comment by Thysbelon** [comment]
Typing as much information as possible will make it easier for me to fix the issue.

The debug output usually has more messages than that. I'm assuming what happened is that the emscripten module didn't run, causing the tool to freeze.

Are you using a PC, a phone, or something else? What browser are you using? What is the version number of your browser?
