### ISSUE TITLE
Sav to Srm?

### ISSUE THREAD

**Issue by AsylumOfMind** [Thysbelon/gbaconv-web#2]
Putting in a .sav is just spitting out .sav rather than .srm, I see no option to change this.

In your readme it says it can do this.

**Comment by Thysbelon** [comment]
Could you please upload your .sav file?

**Comment by Thysbelon** [comment]
I have tested gbaconv-web with save files for Pokémon Leafgreen, Klonoa: Empire of Dreams, and Golden Sun. **All converted to srm successfully**.
The issue you are experiencing is one that no one else has experienced. **If you do not upload your save file for me to test with, I cannot fix this issue for you.**

**Comment by AsylumOfMind** [comment]
I apologize. I did not realise I had not updated my github email and I
rarely check this one. After trying again and running into a different
issue, now I think the problem was that it wasn't actually executing for me
and I mistook another file for output. I had been trying converters without
success for most of the day. Thank you for your help and an awesome tool.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Thysbelon** [comment]
Thank you so much for your response! 😊
