### ISSUE TITLE
Bomberman Max - Blue Champion (USA) (Game Boy Color)

### ISSUE THREAD

**Issue by Darkking65535** [Thysbelon/gbaconv-web#6]
Seemed to give me a blank save when I converted it. Tried changing the extension myself and worked fine. 

home/web_user/savedata.sav
66
79
77
66
69
82
77
65
78
45
filename: /home/web_user/savedata.sav
len: 8192
Detected save type: EEPROM 64kbit
filename: home/web_user/savedata.srm

**Comment by Thysbelon** [comment]
Thank you for opening an issue.
I was unable to recreate your issue. I tested gbaconv-web with a .sav file from Bomberman Max 2 - Blue Advance (USA); the tool successfully converted the .sav to a .srm file.
Your debug message looks normal, except for the first few bytes of the file. They spell "BOMBERMAN-". My tests show that a typical save file should start with "AMREBMOBÒ.2XAM-N".
Please verify the integrity of your .gba file. You can use this [online hashing tool](https://www.romhacking.net/hash/).

**Comment by Thysbelon** [comment]
Ignore my previous message, I just realized something.
You're not talking about a GBA game, you're talking about a Game Boy Color game! I apologize for not realizing this sooner.
I don't believe gbaconv-web currently has support for Game Boy or Game Boy Color games.
I will investigate .srm GB(C) saves, and implement support for them in gbaconv-web, when I have the time to do so.
Thank you for bringing this to my attention!

**Comment by Darkking65535** [comment]
That's alright. I actually used an epilogue operator to pull my save off a
real cartridge. But yeah, it worked when I changed the extension myself, so
you might not have to bother adding support.

**Comment by Thysbelon** [comment]
Closed by 47b42c4
