### ISSUE TITLE
gba save file help

### ISSUE THREAD

**Issue by luhsadzoro** [Thysbelon/gbaconv-web#7]
I have a dsi modded with TwilightMenu++ and played Minish Cap gba on it, but the emulator twilight menu uses breaks at one specific room, so I can't finish the game. I've tried using the GBA EEPROM save fixer to make it able to run on open_agb_firm on 3ds, but it doesn't even read the save file on the 3ds and just makes a new one, and sometimes when it does read it, it just says the save files are corrupted, but they still work on my dsi. If you know anything about this kind of stuff please help me.

**Comment by Thysbelon** [comment]
I believe you are the same person I spoke to before (I have the same username on github and reddit). Unfortunately, I've already told you everything I know. I see that someone else offered to share their save file with you tomorrow; I think that is your best option.

**Comment by luhsadzoro** [comment]
Dang I didn’t even realize lmao. Thanks anyway
